[profile.default]
src = "src"
out = "out"
solc_version = '0.8.26'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
