/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockSealedBidAuction } from "./MockSealedBidAuction";
export type { SealedBidAuction } from "./SealedBidAuction";
